import Link from "next/link";

/** Matches A1–A11, P-1, G-1… as they appear inside caveat prose. */
const CITATION = /\b([AP]-?\d+|G-\d+)\b/g;

/**
 * An assumption reference, made clickable.
 *
 * `docs/ASSUMPTIONS.md` opens by insisting it "is a product surface, not a
 * note… it renders in the UI, one click from every quote". It never did. Every
 * caveat on every card named an assumption — "published as assumption A6",
 * "assumption A10", "assumption P-1" — as inert text, so the sheet the whole
 * argument rests on was one the reader had to go and find.
 */
export function Cite({ id }: { id: string }) {
  return (
    <Link
      href={`/assumptions#${id}`}
      className="mx-0.5 rounded-sm border border-line bg-panel-2 px-1 py-px font-mono text-[0.85em] text-dim no-underline hover:border-accent hover:text-accent"
      title={`Assumption ${id}`}
    >
      {id}
    </Link>
  );
}

/**
 * Render prose, turning every assumption reference inside it into a link.
 *
 * Splitting on a regex rather than rewriting the caveat strings: the text is
 * generated by `tearsheet.generate.build`, and it has to stay identical in the
 * JSON, in `Tearsheet.render`'s terminal output, and here.
 */
export function WithCitations({ text }: { text: string }) {
  const parts: React.ReactNode[] = [];
  let last = 0;

  for (const match of text.matchAll(CITATION)) {
    const at = match.index;
    if (at > last) parts.push(text.slice(last, at));
    parts.push(<Cite key={`${at}-${match[0]}`} id={match[0]} />);
    last = at + match[0].length;
  }
  if (last < text.length) parts.push(text.slice(last));

  return <>{parts}</>;
}
