"""`python -m misquote.tearsheet` — the journal, rendered, with nothing typed in.

    uv run python -m misquote.tearsheet                 # -> docs/TEARSHEET.md
    uv run python -m misquote.tearsheet --agent Grid

`Readme.md`'s definition of done for `docs/TEARSHEET.md` is that no figure in it
is hand-entered: regenerate, and if a number changed, the evidence changed.
`Makefile` has advertised `make tearsheet` since the beginning and pointed it at
`misquote.tearsheet.render`, a module that does not exist — so the one command
that enforces "zero hand-entered numbers" has never run.

`Tearsheet.render()` was already written and already tested. All that was
missing was the entry point.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from misquote.tearsheet.generate import build

REPO = Path(__file__).resolve().parents[3]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--agent", default="Warden")
    parser.add_argument("--journal-dir", default=str(REPO / "data" / "journal"))
    parser.add_argument("--artifacts", default=str(REPO / "apps" / "web" / "public" / "artifacts"))
    parser.add_argument("--out", default=str(REPO / "docs" / "TEARSHEET.md"))
    args = parser.parse_args(argv)

    slug = args.agent.split()[0].lower()
    journal = Path(args.journal_dir) / f"{slug}.jsonl"

    # The replay artifact carries the quote and the pool; the journal carries
    # what a live run actually did. Either may be absent, and the tearsheet is
    # built from whatever exists rather than refusing outright — `build` already
    # renders "no replay yet" and a zero-row journal honestly.
    artifact = Path(args.artifacts) / f"{slug}.json"
    pool = "unknown pool"
    quote = None
    if artifact.exists():
        data = json.loads(artifact.read_text())
        pool = data.get("pool", pool)
        detail = data.get("quote_detail")
        if detail:
            quote = _QuoteView(detail, data.get("quote", ""))

    sheet = build(agent=args.agent, pool=pool, journal_path=journal, quote=quote)

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        f"# Tearsheet — {args.agent}\n\n"
        "<!-- Generated by `make tearsheet`. Every number is derived; do not edit. -->\n\n"
        "```\n" + sheet.render() + "\n```\n"
    )
    print(sheet.render())
    print(f"\n  -> {out}")
    return 0


class _QuoteView:
    """Enough of `replay.ranges.Quote` for `build` to consume, read from JSON.

    The alternative is re-running the replay here, which would make `make
    tearsheet` a sixteen-minute command and let its numbers differ from the
    card's. Reading the artifact means the tearsheet and the card cannot
    disagree: they are the same computation, published once.
    """

    def __init__(self, detail: dict, line: str) -> None:
        self._line = line
        self.sufficient = bool(detail.get("sufficient"))
        self.note = detail.get("note", "")

    def render(self) -> str:
        return self._line


if __name__ == "__main__":
    sys.exit(main())
