"""The allocation driver's books, and the claims its docstring makes.

`replay/driver.py` has `tests/replay/test_engine.py`. This is that file's
sibling, and it exists because the allocation driver shipped with none: the
Router card was generated by code nothing had ever exercised except the run that
produced the card.

The two properties that carry the most weight are the last two. A driver that
pays its costs once and books them somewhere else, or that credits a position
with the rate it *estimated* rather than the rate the market *paid*, produces a
card that is wrong in a direction nobody would notice.
"""

from __future__ import annotations

import pytest

from misquote.agents.router.policy import RouterParams, decide_router
from misquote.core.allocation import AllocationAction
from misquote.estimators.apr import RateEvent
from misquote.replay.allocation import (
    MIN_SAMPLES,
    MIN_WINDOW_HOURS,
    AllocationDriver,
    SwitchCost,
    allocation_quote_from_results,
)

A = "0xfd5840cd36d94d7229439859c0112a4185bc0255"
B = "0xeca88125a5adbe82614ffc12d0db554e2e2867c8"

HOUR = 3600
BASE_INDEX = 1_500_000_000_000_000_000

#: Cash and borrows chosen so utilisation is exactly 0.5, which keeps every
#: hand-computed expectation below readable.
CASH = 100_000_000 * 10**18
BORROWS = 100_000_000 * 10**18


def accrual(market: str, block: int, ts: int, index: int, *, interest: int = 0) -> RateEvent:
    return RateEvent(
        market=market,
        block=block,
        log_index=0,
        ts=ts,
        cash_prior=CASH,
        interest_accumulated=interest,
        borrow_index=index,
        total_borrows=BORROWS,
    )


def tape(market: str, *, hours: int, rate_per_hour: float, start_ts: int = 0, block0: int = 1000):
    """One accrual an hour, growing `borrow_index` by a constant factor."""
    return [
        accrual(market, block0 + i, start_ts + i * HOUR, int(BASE_INDEX * (1 + rate_per_hour) ** i))
        for i in range(hours + 1)
    ]


def segmented(market: str, segments, *, start_ts: int = 0, block0: int = 1000):
    """A tape whose hourly growth rate changes by segment.

    `segments` is a list of `(hours, rate_per_hour)`. Blocks and timestamps
    ascend across the joins, which the estimator enforces — the first draft of
    this fixture restarted block numbers mid-tape and `OutOfOrderError` caught
    it immediately.
    """
    events = []
    index = float(BASE_INDEX)
    ts = start_ts
    block = block0
    for hours, rate in segments:
        for _ in range(hours):
            events.append(accrual(market, block, ts, int(index)))
            index *= 1 + rate
            ts += HOUR
            block += 1
    events.append(accrual(market, block, ts, int(index)))
    return events


def growing_tape(
    market: str, *, hours: int, cash_start: float, cash_end: float, block0: int = 1000
):
    """A tape whose market *size* changes over its length.

    The rate is held constant so the only thing moving is `cash_prior`, which
    is what the A1 ceiling and every `VenueQuote` are built from.
    """
    out = []
    for i in range(hours + 1):
        frac = i / max(1, hours)
        cash = int((cash_start + (cash_end - cash_start) * frac) * 10**18)
        out.append(
            RateEvent(
                market=market,
                block=block0 + i,
                log_index=0,
                ts=i * HOUR,
                cash_prior=cash,
                interest_accumulated=0,
                borrow_index=int(BASE_INDEX * (1 + 1e-5) ** i),
                total_borrows=cash,
            )
        )
    return out


def markets(*ids: str, reserve_factor: float = 0.0, supplied: float = 2e8) -> dict:
    return {
        m: {
            "reserve_factor": reserve_factor,
            "cash_quote": supplied / 2,
            "supplied_base_quote": supplied,
        }
        for m in ids
    }


#: These tapes accrue once an hour, so a 24h window holds ~25 accruals — under
#: `RouterParams`' default `min_apr_samples=30`, which would make every venue
#: unquotable and every test below vacuously "it held". Real vUSDT logs 159,178
#: accruals in seven days, so the default floor is right for the venue and wrong
#: for a readable fixture. The floor itself is exercised in
#: `tests/agents/test_router.py::test_a_venue_below_the_sample_floor_is_not_quotable`.
FIXTURE_PARAMS = RouterParams(min_apr_samples=2)


def fixture_costs(*, gas: float, bps: float) -> SwitchCost:
    """A cost model with chosen numbers, explicitly labelled as a fixture.

    `SwitchCost` has no defaults any more, and that is deliberate: the two it
    used to have decided every figure Router published (P-25). A test that wants
    particular costs has to say so, and say that it is a test.
    """
    return SwitchCost(gas_quote=gas, slippage_bps=bps, basis="fixture", derived=False)


def free_costs() -> SwitchCost:
    """Zero cost, so the hurdle is zero and the boundary is out of the way."""
    return fixture_costs(gas=0.0, bps=0.0)


def driver(mkts, *, capital=10_000.0, costs=None, params=None, interval=HOUR, window=24 * HOUR):
    return AllocationDriver(
        mkts,
        policy=decide_router,
        params=params or FIXTURE_PARAMS,
        capital_quote=capital,
        costs=costs or free_costs(),
        sample_interval_s=interval,
        apr_window_s=window,
    )


def merge(*tapes):
    events = [e for t in tapes for e in t]
    events.sort(key=lambda e: (e.ts, e.block, e.log_index))
    return events


# --- determinism ------------------------------------------------------------


def test_two_runs_over_the_same_tape_are_identical() -> None:
    """The T1 sibling at `test_engine.py`: replay must be reproducible."""
    events = merge(tape(A, hours=72, rate_per_hour=1e-5))
    a = driver(markets(A)).run(events)
    b = driver(markets(A)).run(events)

    assert [str(d.action) for d in a.decisions] == [str(d.action) for d in b.decisions]
    assert a.timestamps == b.timestamps
    assert a.gross_yield_quote == b.gross_yield_quote
    assert a.total_costs == b.total_costs
    assert (a.entries, a.switches, a.exits) == (b.entries, b.switches, b.exits)


def test_a_decision_is_recorded_for_every_sample() -> None:
    events = merge(tape(A, hours=48, rate_per_hour=1e-5))
    result = driver(markets(A)).run(events)
    assert len(result.decisions) == len(result.timestamps) == result.samples
    assert result.timestamps == sorted(result.timestamps)


def test_an_empty_tape_produces_an_empty_result_rather_than_raising() -> None:
    result = driver(markets(A)).run([])
    assert result.samples == 0
    assert result.hours == 0.0


# --- the accumulator is what pays, not the estimate -------------------------


def test_yield_is_booked_from_the_accumulator_not_the_trailing_estimate() -> None:
    """The module docstring's central claim, checked against an exact figure.

    Between two samples the position earns what `borrowIndex` actually moved,
    times utilisation, net of the reserve factor. It does **not** earn the
    trailing APR the policy happened to be looking at — those differ, and paying
    a policy its own estimate is the backtesting equivalent of marking your own
    homework.

    The fixture makes the expectation exact rather than approximate. The tape
    accrues once an hour and the driver samples once an hour, so each step's
    growth is exactly `rate_per_hour`; costs are zero so the notional never
    moves; utilisation is 0.5 by construction and the reserve factor is 0. The
    whole booked yield is therefore

        capital x invested_samples x rate x 0.5

    with no free parameters. The first draft of this test asserted only that the
    booked figure *differed* from a hand-rolled annualised one, and a mutation
    that paid the position `fit.supply_apr x interval / year` passed it — a test
    that cannot fail is worse than no test.
    """
    rate = 1e-5
    capital = 10_000.0
    events = merge(tape(A, hours=72, rate_per_hour=rate))
    result = driver(markets(A, reserve_factor=0.0), capital=capital).run(events)

    assert result.entries == 1, "with zero costs the hurdle is zero and it should enter"
    assert result.total_costs == 0.0
    assert result.invested_samples > 0

    expected = capital * result.invested_samples * rate * 0.5
    assert result.gross_yield_quote == pytest.approx(expected, rel=1e-6), (
        "booked yield does not equal the accumulator's growth over the samples "
        "the position was held for — the driver is crediting something else"
    )


def test_a_flat_accumulator_pays_nothing() -> None:
    """borrowIndex that never moves is a market that never paid."""
    events = merge(tape(A, hours=48, rate_per_hour=0.0))
    result = driver(markets(A)).run(events)
    assert result.gross_yield_quote == 0.0


def test_the_reserve_factor_reduces_what_the_supplier_is_paid() -> None:
    events = merge(tape(A, hours=48, rate_per_hour=1e-5))
    none_reserved = driver(markets(A, reserve_factor=0.0)).run(events)
    half_reserved = driver(markets(A, reserve_factor=0.5)).run(events)
    assert half_reserved.gross_yield_quote == pytest.approx(
        none_reserved.gross_yield_quote * 0.5, rel=1e-9
    )


# --- costs -----------------------------------------------------------------


#: Leadership alternates three times, each swing large enough to clear a hurdle
#: set by a few basis points of slippage. Built once and shared, because both
#: cost tests need repeated moves and a fixture that produces only one entry
#: cannot tell a per-move charge from a single one.
ALTERNATING = (
    (24, 1e-3),  # A leads
    (24, 1e-7),  # B leads
    (24, 1e-3),  # A again
    (24, 1e-7),  # B again
)
MIRRORED = tuple((h, 1e-7 if r == 1e-3 else 1e-3) for h, r in ALTERNATING)

MOVING_PARAMS = RouterParams(
    min_apr_samples=2, persistence_samples=1, cooldown_s=0, max_switches_per_day=1000
)


def alternating_tape():
    return merge(
        segmented(A, ALTERNATING, block0=1000),
        segmented(B, MIRRORED, block0=50_000),
    )


def test_every_move_is_charged_not_only_the_first() -> None:
    """`test_engine.py` asserts this for the range driver; the same must hold here."""
    costs = fixture_costs(gas=1.0, bps=0.0)
    result = driver(markets(A, B), costs=costs, params=MOVING_PARAMS).run(alternating_tape())

    assert result.moves >= 2, "the tape did not produce repeated moves, so this proves nothing"
    # Gas only, no slippage: every move costs exactly 2 x gas, regardless of notional.
    assert result.total_costs == pytest.approx(result.moves * 2.0 * costs.gas_quote, rel=1e-9)


def test_the_cost_charged_and_the_cost_recorded_are_the_same_number() -> None:
    """They were two calls against two different notionals.

    `value` was reduced by `_move_cost(value)` while `total_costs` grew by
    `_move_cost(capital_quote)`. Slippage is a fraction of notional, so after
    the **first** move the position and the books describe different positions —
    and `net_quote` is computed from the books.

    This needs more than one move to bite, which is why the first version of
    this test did not catch the defect it was written for: with a single entry,
    `value` still equals `capital_quote` and the two calls agree.

    With slippage `s` charged on the declining value, `m` moves cost

        C.s + C(1-s).s + C(1-s)^2.s + ... = C.(1 - (1-s)^m)

    which is strictly less than the `m . C . s` a capital-based charge books.
    """
    slippage_bps = 10.0
    s_frac = slippage_bps / 10_000.0
    capital = 10_000.0
    costs = fixture_costs(gas=0.0, bps=slippage_bps)

    result = driver(markets(A, B), costs=costs, params=MOVING_PARAMS, capital=capital).run(
        alternating_tape()
    )

    # Switches, not moves. Entering and exiting hold the underlying they
    # already have and pay gas only — charging them the pool fee was a phantom
    # cost worth roughly nine tenths of Router's advertised advantage, and
    # `_move_cost`'s `swaps` argument is the correction.
    k = result.switches
    assert k >= 2, "fewer than two switches, so the two formulas cannot be told apart"

    on_declining_value = capital * (1 - (1 - s_frac) ** k)
    on_capital_each_time = k * capital * s_frac

    assert result.total_costs == pytest.approx(on_declining_value, rel=1e-9), (
        "the books do not match what was actually deducted from the position"
    )
    assert result.total_costs != pytest.approx(on_capital_each_time, rel=1e-12), (
        "total_costs matches a capital-based charge, which is the defect this "
        "test exists for — the position was charged on its current value"
    )


def test_zero_cost_means_zero_hurdle_and_a_positive_rate_enters() -> None:
    """Pins the boundary the tests above rely on, so they cannot pass vacuously."""
    events = merge(tape(A, hours=48, rate_per_hour=1e-5))
    result = driver(markets(A)).run(events)
    assert result.entries == 1
    assert any(d.action is AllocationAction.ENTER for d in result.decisions)


# --- A1: refuse rather than clamp -------------------------------------------


def test_a_position_above_the_epsilon_ceiling_is_counted_and_the_quote_refused() -> None:
    """P-14, in the venue the same argument applies to.

    Supplying moves utilisation and therefore the rate, so a position larger
    than eps of the market's supplied base is not a replay of that market. A1
    says such a quote is refused rather than rendered.
    """
    params = RouterParams(eps_market_share=0.01, min_apr_samples=2, persistence_samples=1)
    # Market size now comes from the tape, not from the markets dict — that is
    # the whole point of the look-ahead fix below. A tiny market against a large
    # position: supplied base is 2,000 and 1% of it is 20, against 10,000.
    events = growing_tape(A, hours=72, cash_start=1_000.0, cash_end=1_000.0)
    result = driver(markets(A), params=params, capital=10_000.0).run(events)

    assert result.a1_capped > 0, "the ceiling was breached and nothing counted it"

    quote = allocation_quote_from_results(
        [result], windows=1, perturbation_count=1, capital_quote=10_000.0
    )
    assert not quote.sufficient
    assert "A1" in quote.note and "refused" in quote.note


def test_a_position_inside_the_ceiling_is_not_counted() -> None:
    """The other direction, so the check above is not simply always true."""
    params = RouterParams(eps_market_share=0.01, min_apr_samples=2, persistence_samples=1)
    events = growing_tape(A, hours=72, cash_start=1e9, cash_end=1e9)
    result = driver(markets(A), params=params, capital=10_000.0).run(events)
    assert result.a1_capped == 0


# --- the publication floors -------------------------------------------------


def test_too_few_windows_is_withheld_not_quoted() -> None:
    events = merge(tape(A, hours=72, rate_per_hour=1e-5))
    result = driver(markets(A)).run(events)
    quote = allocation_quote_from_results(
        [result], windows=1, perturbation_count=1, capital_quote=10_000.0
    )
    assert not quote.sufficient
    assert f"requires {MIN_SAMPLES}" in quote.note


def test_a_window_shorter_than_the_policy_horizon_is_named_as_such() -> None:
    """`ranges.py` refuses these and says why; so must this."""
    short = merge(tape(A, hours=2, rate_per_hour=1e-5))
    results = [driver(markets(A)).run(short) for _ in range(MIN_SAMPLES + 5)]
    assert all(0 < r.hours < MIN_WINDOW_HOURS for r in results)

    quote = allocation_quote_from_results(
        results, windows=len(results), perturbation_count=1, capital_quote=10_000.0
    )
    assert not quote.sufficient
    assert "shorter than the" in quote.note


def test_enough_long_windows_produce_a_quote() -> None:
    """Without this, every refusal test above could pass on a function that
    refuses unconditionally."""
    events = merge(tape(A, hours=72, rate_per_hour=1e-5))
    results = [driver(markets(A)).run(events) for _ in range(MIN_SAMPLES)]
    quote = allocation_quote_from_results(
        results, windows=MIN_SAMPLES, perturbation_count=1, capital_quote=10_000.0
    )
    assert quote.sufficient, quote.note
    assert quote.p25 <= quote.p50 <= quote.p75


# --- staleness and refusal to route -----------------------------------------


def test_a_market_that_stops_accruing_goes_stale_and_is_left() -> None:
    """A held venue whose rate can no longer be measured is exited, not held.

    The tape stops early for A while sample times continue, so its trailing
    window empties.
    """
    params = RouterParams(min_apr_samples=2, persistence_samples=1, cooldown_s=0)
    a = tape(A, hours=30, rate_per_hour=1e-4)
    # B keeps accruing so sample times continue past A's last event.
    b = tape(B, hours=96, rate_per_hour=1e-9, block0=9000)
    result = driver(markets(A, B), params=params, window=6 * HOUR).run(merge(a, b))
    assert result.exits >= 1 or result.switches >= 1, (
        "A stopped accruing and the position neither left nor moved"
    )


def test_the_driver_refuses_a_venue_set_it_cannot_choose_from() -> None:
    with pytest.raises(ValueError, match="at least one venue"):
        AllocationDriver({}, policy=decide_router, params=RouterParams(), capital_quote=1.0)


# --- market size must not come from the future ------------------------------


def test_a_venue_quote_reports_the_market_as_it_was_at_that_sample() -> None:
    """The direct statement: supplied base must move with the tape.

    If market size is taken from `rows[-1]` this is constant across the run and
    the assertion fails on its own terms.
    """
    events = growing_tape(A, hours=72, cash_start=1_000.0, cash_end=10_000.0)
    result = driver(markets(A), params=FIXTURE_PARAMS, capital=1.0).run(events)

    sizes = [
        d.reason("supplied_base_quote")
        for d in result.decisions
        if d.reason("supplied_base_quote") is not None
    ]
    assert sizes, "the decision does not journal the market size it was given"
    assert sizes[0] != sizes[-1], (
        "supplied base is identical at the start and end of a tape whose market "
        "grew tenfold — it is being read from one fixed point, not per sample"
    )
    assert sizes == sorted(sizes), "market size should follow the tape's own growth"
