"""Tick <-> sqrt-price conversion, ported bit-for-bit from Uniswap v3 `TickMath`.

PancakeSwap v3 uses Uniswap v3's core math unchanged, so this is a port of the
canonical library rather than an approximation of it. Every function returns the
exact integer the Solidity returns, and `tests/core/test_tickmath.py` proves that
against vectors generated by the real contract.

Why a hand port instead of a library: the published Python packages for v3 math
are float-based. A float `sqrtPriceX96` cannot be compared to a contract's output
for equality, only for tolerance — and tolerance is precisely what hides the
off-by-one errors this code exists to not have. The whole differential-testing
strategy depends on these being integers all the way down.

Reference: Uniswap v3-core `contracts/libraries/TickMath.sol`.
"""

from __future__ import annotations

# The tick range is bounded by where a Q64.96 sqrt price stops being representable.
MIN_TICK = -887272
MAX_TICK = 887272

MIN_SQRT_RATIO = 4295128739
MAX_SQRT_RATIO = 1461446703485210103287273052203988822378723970342

Q96 = 1 << 96
Q128 = 1 << 128
UINT256_MAX = (1 << 256) - 1

# One magic constant per bit of |tick|, each the Q128.128 fixed-point value of
# 1.0001^(-2^i / 2). Multiplying the subset selected by the set bits of |tick|
# evaluates 1.0001^(-tick/2) in twenty multiplications instead of a loop over
# 887272 of them. Taken verbatim from TickMath.sol; do not recompute them in
# floating point, which is how a rounding error gets introduced at the source.
_RATIOS: tuple[tuple[int, int], ...] = (
    (0x2, 0xFFF97272373D413259A46990580E213A),
    (0x4, 0xFFF2E50F5F656932EF12357CF3C7FDCC),
    (0x8, 0xFFE5CACA7E10E4E61C3624EAA0941CD0),
    (0x10, 0xFFCB9843D60F6159C9DB58835C926644),
    (0x20, 0xFF973B41FA98C081472E6896DFB254C0),
    (0x40, 0xFF2EA16466C96A3843EC78B326B52861),
    (0x80, 0xFE5DEE046A99A2A811C461F1969C3053),
    (0x100, 0xFCBE86C7900A88AEDCFFC83B479AA3A4),
    (0x200, 0xF987A7253AC413176F2B074CF7815E54),
    (0x400, 0xF3392B0822B70005940C7A398E4B70F3),
    (0x800, 0xE7159475A2C29B7443B29C7FA6E889D9),
    (0x1000, 0xD097F3BDFD2022B8845AD8F792AA5825),
    (0x2000, 0xA9F746462D870FDF8A65DC1F90E061E5),
    (0x4000, 0x70D869A156D2A1B890BB3DF62BAF32F7),
    (0x8000, 0x31BE135F97D08FD981231505542FCFA6),
    (0x10000, 0x9AA508B5B7A84E1C677DE54F3E99BC9),
    (0x20000, 0x5D6AF8DEDB81196699C329225EE604),
    (0x40000, 0x2216E584F5FA1EA926041BEDFE98),
    (0x80000, 0x48A170391F7DC42444E8FA2),
)

# log_2 -> log_1.0001, and the two correction bounds that decide whether the
# recovered tick is the floor or the one above it.
_LOG_SQRT_10001 = 255738958999603826347141
_TICK_LOW_ERROR = 3402992956809132418596140100660247210
_TICK_HIGH_ERROR = 291339464771989622907027621153398088495


class TickMathError(ValueError):
    """A tick or sqrt price outside the range v3 can represent."""


def get_sqrt_ratio_at_tick(tick: int) -> int:
    """sqrt(1.0001^tick) as a Q64.96 fixed-point integer.

    Exact: matches `TickMath.getSqrtRatioAtTick` for every tick in range.
    """
    abs_tick = -tick if tick < 0 else tick
    if abs_tick > MAX_TICK:
        raise TickMathError(f"tick {tick} outside [{MIN_TICK}, {MAX_TICK}]")

    ratio = (
        0xFFFCB933BD6FAD37AA2D162D1A594001
        if abs_tick & 0x1
        else 0x100000000000000000000000000000000
    )
    for bit, factor in _RATIOS:
        if abs_tick & bit:
            ratio = (ratio * factor) >> 128

    # The constants encode negative powers, so a positive tick is the reciprocal.
    if tick > 0:
        ratio = UINT256_MAX // ratio

    # Q128.128 -> Q128.96, rounding up, so the result never understates the price
    # at a tick boundary.
    return (ratio >> 32) + (1 if ratio % (1 << 32) else 0)


def get_tick_at_sqrt_ratio(sqrt_price_x96: int) -> int:
    """The greatest tick whose sqrt ratio is <= `sqrt_price_x96`.

    Exact: matches `TickMath.getTickAtSqrtRatio`. Note the asymmetric bound —
    `MAX_SQRT_RATIO` itself is excluded, because it is the ratio *above* MAX_TICK.
    """
    if not (MIN_SQRT_RATIO <= sqrt_price_x96 < MAX_SQRT_RATIO):
        raise TickMathError(
            f"sqrt ratio {sqrt_price_x96} outside [{MIN_SQRT_RATIO}, {MAX_SQRT_RATIO})"
        )

    ratio = sqrt_price_x96 << 32

    # Solidity finds the most significant bit with a byte-wise binary search;
    # `int.bit_length` computes the identical value directly.
    msb = ratio.bit_length() - 1

    r = ratio >> (msb - 127) if msb >= 128 else ratio << (127 - msb)
    log_2 = (msb - 128) << 64

    # Fourteen squarings recover fourteen fractional bits of log2(ratio). Each
    # round squares in Q128.128, and the carry out of bit 128 is the next bit.
    for shift in range(63, 49, -1):
        r = (r * r) >> 127
        f = r >> 128
        log_2 |= f << shift
        r >>= f

    log_sqrt_10001 = log_2 * _LOG_SQRT_10001

    tick_low = (log_sqrt_10001 - _TICK_LOW_ERROR) >> 128
    tick_high = (log_sqrt_10001 + _TICK_HIGH_ERROR) >> 128

    if tick_low == tick_high:
        return tick_low
    return tick_high if get_sqrt_ratio_at_tick(tick_high) <= sqrt_price_x96 else tick_low


def nearest_usable_tick(tick: int, tick_spacing: int) -> int:
    """Round to the nearest tick the pool will actually accept, staying in range.

    Only multiples of the fee tier's spacing can bound a position. Ties round to
    the even multiple, matching Python's `round`, because a consistent tie rule
    keeps replay reproducible.
    """
    if tick_spacing <= 0:
        raise TickMathError(f"tick spacing must be positive, got {tick_spacing}")
    if not (MIN_TICK <= tick <= MAX_TICK):
        raise TickMathError(f"tick {tick} outside [{MIN_TICK}, {MAX_TICK}]")

    rounded = round(tick / tick_spacing) * tick_spacing
    if rounded < MIN_TICK:
        return rounded + tick_spacing
    if rounded > MAX_TICK:
        return rounded - tick_spacing
    return int(rounded)


def floor_to_spacing(tick: int, tick_spacing: int) -> int:
    """Round down to a usable tick. Floor division, so negative ticks go down too."""
    if tick_spacing <= 0:
        raise TickMathError(f"tick spacing must be positive, got {tick_spacing}")
    return (tick // tick_spacing) * tick_spacing


def price_to_tick(price: float, dec0: int, dec1: int) -> int:
    """Human price (token1 per token0) -> the tick at or below it.

    Display and configuration only. Never call this inside an accounting path —
    it goes through a float, and every number that settles stays an integer.
    """
    import math

    raw = price * (10 ** (dec1 - dec0)) if dec1 >= dec0 else price / (10 ** (dec0 - dec1))
    return math.floor(math.log(raw) / math.log(1.0001))


def tick_to_price(tick: int, dec0: int, dec1: int) -> float:
    """Tick -> human price (token1 per token0), decimal-adjusted.

    Display only, for the same reason as `price_to_tick`.
    """
    raw = 1.0001 ** float(tick)
    return raw / (10 ** (dec1 - dec0)) if dec1 >= dec0 else raw * (10 ** (dec0 - dec1))


def sqrt_ratio_to_price(sqrt_price_x96: int, dec0: int, dec1: int) -> float:
    """Q64.96 sqrt ratio -> human price (token1 per token0). Display only."""
    raw = (sqrt_price_x96 / Q96) ** 2
    return raw / (10 ** (dec1 - dec0)) if dec1 >= dec0 else raw * (10 ** (dec0 - dec1))
