"""Bring the measurable numbers in the judge's document up to date.

    uv run python scripts/sync_docs.py          # rewrite them
    uv run python scripts/sync_docs.py --check  # fail if they are stale

`docs/FOR_JUDGES.md` opens with commands and tells a judge to run them, so its
figures are checked more often than anything else here. They have drifted three
times — "395 tests" against a suite of 463, "455 tests: 436 offline" against
482, and `localhost:8080` after `make web` moved to 3000 — and each hand
correction drifted again within hours.

The project's answer to that everywhere else is to derive the number rather than
type it: `make showcase` regenerates the cards, `make assumptions` regenerates
the sheet. This is the same move for the one document that is prose. Add a test,
run `make judges`, and the sentence that quotes the count changes with it.

`tests/web/test_docs_match_reality.py` asserts the result, so a stale figure is
a failing test rather than something a reader has to notice.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
JUDGES = REPO / "docs" / "FOR_JUDGES.md"
MAKEFILE = REPO / "Makefile"


def collected() -> tuple[int, int]:
    """(offline, total), straight from pytest's own collector."""
    result = subprocess.run(
        [sys.executable, "-m", "pytest", "--collect-only", "-q", "-p", "no:cacheprovider"],
        cwd=REPO,
        capture_output=True,
        text=True,
        timeout=180,
        check=False,
    )
    text = result.stdout + result.stderr

    split = re.search(r"(\d+)/(\d+) tests collected", text)
    if split:
        return int(split.group(1)), int(split.group(2))
    plain = re.search(r"(\d+) tests collected", text)
    if plain:
        return int(plain.group(1)), int(plain.group(1))

    raise SystemExit(f"could not read a collection count from pytest:\n{text[-800:]}")


def web_port() -> str:
    """The port `make web` advertises in its own help text."""
    match = re.search(r"^web:.*?##.*?localhost:(\d+)", MAKEFILE.read_text(), re.MULTILINE)
    if not match:
        raise SystemExit("the `web` target no longer names a port in its help text")
    return match.group(1)


# --- derived blocks ---------------------------------------------------------
#
# Regex substitution works for a figure inside a sentence and is fragile across
# a multi-line table. Blocks are delimited instead and regenerated wholesale, so
# the contract — this is derived, do not hand-edit — is visible in the document
# rather than only here.
#
# The document currently carries **two contradictory tables of the same result**
# ninety lines apart, one of them a stale copy of a synthetic run with a whole
# narrative resting on it. That is what a hand-typed table costs, and it is not
# a mistake anyone makes on purpose: it is what happens when the artifact is
# regenerated and the prose is not.

BLOCK = "<!-- derived:{name} — regenerated by `make judges`; do not hand-edit -->"
BLOCK_END = "<!-- /derived:{name} -->"


def _artifact(name: str) -> dict | None:
    """One published artifact, or None if it has not been generated."""
    import json

    path = REPO / "apps" / "web" / "public" / "artifacts" / name
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text())
    except (OSError, json.JSONDecodeError):
        return None


def advantage_block() -> list[str] | None:
    """The Δ table, from the artifact the judged claim is made of.

    Carries each task's `source` and `capital_quote` beside its numbers, because
    task 3 runs at the capital assumption A1 permits on the shallower of its two
    venues — a different figure from tasks 1 and 2 — and a table that hid that
    would be comparing three returns computed on different bases.
    """
    payload = _artifact("advantage.json")
    if not payload or not payload.get("tasks"):
        return None

    rows = [
        "| Task | Tape | Capital | DIY | Agent | Δ median |",
        "|---|---|---|---|---|---|",
    ]
    for task in payload["tasks"]:
        name = task["task"].split("—")[0].strip()
        base, agent = task["baseline"], task["agent"]
        if not task.get("quotable", True):
            rows.append(
                f"| {name} | `{task.get('source', '?')}` | "
                f"{task.get('capital_quote', 0):.4g} | — | — | **withheld** |"
            )
            continue
        rows.append(
            f"| {name} | `{task.get('source', '?')}` | {task.get('capital_quote', 0):.4g} | "
            f"{base['p25']:.2f} – {base['p75']:.2f}% | "
            f"{agent['p25']:.2f} – {agent['p75']:.2f}% | "
            f"**{task['delta_pp']:+.2f}pp** |"
        )
    return rows


def tape_block() -> list[str] | None:
    """Swaps and unbroken coverage per pool, from the tape itself.

    Coverage rather than span: a database holding one day at each end of a
    twenty-six day gap reports "26 days" from `max(ts) - min(ts)` and is what
    every interrupted backfill leaves. `store.covered_span` is what the go/no-go
    gate already uses, for the same reason.
    """
    import sqlite3

    db = REPO / "data" / "misquote.db"
    if not db.exists():
        return None

    from misquote.chain.addresses import known_pools_on
    from misquote.indexer import store

    conn = sqlite3.connect(db)
    conn.row_factory = sqlite3.Row
    rows = ["| Pool | Swaps | Unbroken blocks read |", "|---|---|---|"]
    try:
        for pool in known_pools_on(56):
            address = pool.address.lower()
            count = conn.execute("SELECT count(*) FROM swap WHERE pool = ?", (address,)).fetchone()[
                0
            ]
            if not count:
                continue
            try:
                span = store.covered_span(conn, address)
            except sqlite3.OperationalError:
                span = None
            blocks = f"{span[1] - span[0] + 1:,}" if span else "not recorded"
            rows.append(f"| {pool.label} | {count:,} | {blocks} |")
    finally:
        conn.close()
    return rows if len(rows) > 2 else None


def registry_block() -> list[str] | None:
    """What the ERC-8004 survey found, replacing three hand-typed figures.

    The population moves — roughly 1,100 registrations an hour were observed
    while this was being written — so a number typed here is stale by the time
    it is read.
    """
    payload = _artifact("registry.json")
    identity = (payload or {}).get("identity") or {}
    if not identity.get("surveyed"):
        return None

    sampled = identity.get("sampled", 0)
    ids = identity.get("sampled_ids") or []
    if not sampled:
        return None

    intervals = identity.get("intervals") or {}

    def share(key: str) -> str:
        """A share and the interval it is worth to this many observations.

        Never the point alone. At n=40 "30% substantive" spans 18-46%, and
        printing the 30% by itself is the false precision this project is named
        against — on the page that criticises other marketplaces for it.
        """
        value = identity.get(key, 0)
        text = f"{value} / {sampled} ({value / sampled:.0%})"
        bounds = intervals.get(key)
        if bounds:
            text += f" · 95% CI {bounds['low']:.0%}–{bounds['high']:.0%}"
        return text

    return [
        "| | |",
        "|---|---|",
        f"| agent ids the registry resolves | **{identity.get('population', 0):,}** |",
        f"| sampled | {sampled}, spanning ids {min(ids):,}–{max(ids):,}"
        + (
            f"; {identity['listings_shown']} published as cards |"
            if identity.get("listings_shown")
            else " |"
        )
        if ids
        else f"| sampled | {sampled} |",
        f"| card resolves | {share('resolvable')} |",
        f"| declares itself active | {share('declared_active')} |",
        f"| **describes a service** | **{share('with_endpoint')}** |",
        f"| **substantive** | **{share('substantive')}** |",
    ]


def mechanism_block() -> list[str] | None:
    """How the agent spent its actions, from the task with the most of them.

    The figures P-20 turns on. They live on the artifact only once a report has
    been generated by a build that records `mints`/`pulls`/`recentres` — before
    that this returns None and `fill_blocks` leaves the block alone rather than
    replacing a true statement with an empty one.

    Uses the worst task rather than an average: "the agent never recentres" is a
    claim about behaviour, and averaging it across a task that was withheld
    would soften it into something nobody measured.
    """
    payload = _artifact("advantage.json")
    tasks = [t for t in (payload or {}).get("tasks", []) if t.get("quotable")]
    if not tasks:
        return None

    task = min(tasks, key=lambda t: t.get("delta_pp", 0.0))
    agent = task.get("agent") or {}
    if "mints" not in agent or not task.get("replay_days"):
        return None

    days = task["replay_days"]
    cycles = min(agent.get("mints", 0), agent.get("pulls", 0))
    capital = task.get("capital_quote") or 0.0
    gas_share = (agent.get("costs", 0.0) / capital) if capital else 0.0

    rows = [
        f"    MINT {agent.get('mints', 0)} · PULL {agent.get('pulls', 0)} · "
        f"RECENTRE {agent.get('recentres', 0)}",
        f"    {cycles / days:.1f} pull-and-re-mint cycles per calendar day, "
        "against max_rebalances_per_day",
        f"    in range {agent.get('in_range', 0.0):.1%} of the window; "
        f"gas alone {gas_share * 365 / days:.0%} of capital annualised",
    ]
    # Two header rows are stripped by the row count in `fill_blocks`; this block
    # is a code fence rather than a table, so pad the count honestly.
    return ["```", *rows, "```", ""]


def _venue_mix(card: dict) -> str:
    """What Router actually replayed over, counted from the card.

    This read "{hours}h of Venus accruals", which was true while Venus was the
    only kind of venue and stopped being true the moment a PancakeSwap range
    became one. The row is in the document a judge is pointed at first, and it
    named one of the two venue types the run considered.

    Counted rather than described, so it cannot go stale the same way twice.
    """
    hours = card.get("replay", {}).get("hours", 0)
    venues = card.get("venues", [])
    lending = sum(1 for v in venues if v.get("kind") != "pool")
    pools = sum(1 for v in venues if v.get("kind") == "pool")
    parts = []
    if lending:
        parts.append(f"{lending} Venus market{'s' if lending != 1 else ''}")
    if pools:
        parts.append(f"{pools} PancakeSwap v3 range{'s' if pools != 1 else ''}")
    return f"{hours:.0f}h across {' and '.join(parts)}" if parts else f"{hours:.0f}h"


def router_block() -> list[str] | None:
    """Router's figures, read from its card instead of retyped into prose.

    Every one of these has now been wrong in a document at least once. They move
    for reasons that have nothing to do with anybody editing the docs — a longer
    rate tape changed the venue leadership, and the annualisation gate flipped
    the published quote between a period figure and an annual one the moment the
    windows crossed 168 hours. Prose cannot track that; a derived block can.
    """
    card = _artifact("router.json")
    if not card:
        return None

    quote, replay = card.get("quote", {}), card.get("replay", {})
    if not quote or not replay:
        return None

    def pct(x: float) -> str:
        return f"{100 * x:.2f}%"

    band = f"{quote['p25']:.2f}% – {quote['p75']:.2f}%" if quote.get("sufficient") else "withheld"
    period = (
        "annualised"
        if quote.get("annualised")
        else f"over {quote.get('hours_per_window', 0):.0f}h, not annualised"
    )

    return [
        "| | |",
        "|---|---|",
        f"| Tape | {_venue_mix(card)} |",
        f"| Net return on supplied capital | **{band}** ({period}) |",
        f"| Best realized rate seen | {pct(replay.get('best_apr_seen', 0))} |",
        f"| Round-trip hurdle | {pct(replay.get('hurdle_apr_p50', 0))} |",
        f"| Largest gap between venues | {pct(replay.get('max_edge_apr', 0))} |",
        (
            f"| Moves | {replay.get('entries', 0)} enter · "
            f"{replay.get('switches', 0)} switch · {replay.get('exits', 0)} exit |"
        ),
        f"| Held the better-paying venue | {100 * replay.get('best_venue_fraction', 0):.0f}% of samples |",
        (
            f"| Earned / cost | {replay.get('gross_yield_quote', 0):,.2f} against "
            f"{replay.get('costs_quote', 0):,.4f} |"
        ),
        (
            f"| Commitment before entry repays a round trip | "
            f"{replay.get('breakeven_horizon_hours', 0) / 24:.1f} days |"
        ),
        f"| vs parking in the best venue | {card.get('advantage', {}).get('verdict', '—')} |",
    ]


BLOCKS = {
    "router": router_block,
    "advantage": advantage_block,
    "tape": tape_block,
    "registry": registry_block,
    "mechanism": mechanism_block,
}


def fill_blocks(text: str) -> tuple[str, list[str]]:
    """Regenerate every delimited block whose source artifact exists.

    A block whose artifact has not been generated is **left exactly as it is**
    rather than emptied. Blanking it would delete a true statement because a
    file was missing, which is a worse failure than the staleness this guards.
    """
    changes: list[str] = []
    for name, build in BLOCKS.items():
        start, end = BLOCK.format(name=name), BLOCK_END.format(name=name)
        if start not in text or end not in text:
            continue
        rows = build()
        if rows is None:
            changes.append(f"!! {name}: source artifact missing — block left untouched")
            continue

        head = text.index(start) + len(start)
        tail = text.index(end)
        replacement = "\n" + "\n".join(rows) + "\n"
        if text[head:tail] != replacement:
            changes.append(f"{name} block -> {len(rows) - 2} row(s)")
            text = text[:head] + replacement + text[tail:]
    return text, changes


def rewrite(text: str) -> tuple[str, list[str]]:
    """Return the corrected document and a note of what moved."""
    offline, total = collected()
    port = web_port()
    changes: list[str] = []

    def sub(pattern: str, replacement, label: str) -> None:
        nonlocal text
        updated, count = re.subn(pattern, replacement, text, flags=re.MULTILINE)
        if count == 0:
            changes.append(f"!! {label}: pattern not found — has it been reworded?")
        elif updated != text:
            changes.append(label)
            text = updated

    sub(
        r"(make test\s+#\s*)(\d[\d,]*)( tests)",
        lambda m: f"{m.group(1)}{offline:,}{m.group(3)}".replace(",", ","),
        f"quickstart test count -> {offline}",
    )
    sub(
        r"(\*\*)(\d[\d,]*)( tests: )(\d[\d,]*)( offline, )(\d[\d,]*)( against a live chain)",
        lambda m: (
            f"{m.group(1)}{total}{m.group(3)}{offline}{m.group(5)}{total - offline}{m.group(7)}"
        ),
        f"headline counts -> {total}: {offline} offline, {total - offline} chain",
    )
    sub(
        r"(make web\s+#\s*http://localhost:)(\d+)",
        lambda m: f"{m.group(1)}{port}",
        f"web port -> {port}",
    )

    # Line counts quoted beside a path, e.g. "| The policy, 486 lines, pure |".
    def fix_lines(match: re.Match[str]) -> str:
        path = REPO / match.group(3)
        if not path.exists():
            return match.group(0)
        actual = len(path.read_text().splitlines())
        if int(match.group(2).replace(",", "")) == actual:
            return match.group(0)
        changes.append(f"{match.group(3)} -> {actual} lines")
        return match.group(0).replace(f"{match.group(2)} lines", f"{actual} lines", 1)

    text = re.sub(r"\|([^|]*?(\d[\d,]*) lines[^|]*?)\|\s*`([^`]+\.py)`\s*\|", fix_lines, text)

    text, block_changes = fill_blocks(text)
    changes.extend(block_changes)

    return text, changes


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="report staleness, write nothing")
    args = parser.parse_args()

    original = JUDGES.read_text()
    updated, changes = rewrite(original)

    if not changes:
        print(f"  {JUDGES.relative_to(REPO)} is current")
        return 0

    for change in changes:
        print(f"  {change}")

    # A `!!` line is a *warning*, not staleness: a block whose source artifact
    # has not been generated is left exactly as it is, and a sentence that was
    # reworded is reported so somebody can look at it. Neither means the
    # document disagrees with an artifact, and conflating them would make the
    # go/no-go gate amber for a report nobody has run yet — which teaches people
    # to ignore it, the failure mode `tests/chain/conftest.py` already argues
    # about at length for the chain suite.
    drift = [change for change in changes if not change.startswith("!!")]

    if args.check:
        if not drift:
            print("\n  warnings only — nothing disagrees with an artifact")
            return 0
        print("\n  stale — run `make judges`")
        return 1

    JUDGES.write_text(updated)
    print(f"\n  -> {JUDGES.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
